### ISSUE TITLE
Migrate away from JCenter

### ISSUE THREAD

**Issue by steffandroid** [pengrad/jdk9-deps#1]
[JFrog](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) has announced that it will be shutting down JCenter on February 2nd 2022. JCenter is the sole repository hosting this library, so it will become unavailable after this date unless migrated to an alternative service.

**Comment by jboxx** [comment]
Need to close this issue since it's already on mavenCentral 
https://mvnrepository.com/artifact/com.github.pengrad/jdk9-deps/1.0

**Comment by steffandroid** [comment]
Awesome, thanks!

**Comment by steffandroid** [comment]
@jboxx according to that link, this library is only on JCenter:
<img width="549" alt="Screenshot 2021-02-15 at 11 46 32" src="https://user-images.githubusercontent.com/4996463/107936929-86544280-6f83-11eb-9fcf-a5ca88a33986.png">
There's no entry for it under the author's group ID on [Maven Central](https://search.maven.org/search?q=g:com.github.pengrad)

**Comment by steffandroid** [comment]
Update: JCenter will remain up indefinitely as a read-only repository.
